version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/node:10.12.0
    steps:
       - run: echo "hello to C.CI  tests under control of rohmmel , yes it's already done test 500 "
          
          
