version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/node:10.12.0
    steps:
      - run:
          name: Deploy master
          command:  ssh -o "StrictHostKeyChecking no" root@192.81.218.25 'bash -l -c "source /root/.bashrc; cd ~/index-site;chmod 777 build.sh;npm run start"'
